# 不用 Kustomization，因為用了的話，會導致 namespace 被覆蓋成 `prod`，而不是 `argocd`。
# 用法：`kubectl apply -f application.yaml`
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: instavote
  source:
    path: prod
    repoURL: https://github.com/drxaero/udemy-argo-labs.git
    targetRevision: release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Server-Side-Apply=true
      - Retry=true
    retry:
      limit: 5 # Maximum num of retries
      backoff:
        duration: 5s    # Initial retry interval
        factor: 2       # Multiplication factor for the backoff
        maxDuration: 1m # Maximum retry interval
