# 不用 Kustomization，因為用了的話，會導致 namespace 被覆蓋成 `prod`，而不是 `argocd`。
# 用法：`kubectl apply -f application.yaml`
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: instavote
  source:
    path: prod
    repoURL: https://github.com/drxaero/udemy-argo-labs.git
    targetRevision: release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Server-Side-Apply=true
